export const ROUTES = {
  HOME: "/",
  COLLECTION:"/collection",
  PAGE2:"/page2",
  DASHBOARD:"/admin/",
  PAGE_LIST:"/admin/page",
  CONTACTUS_FORM:"/admin/contactus",
  ADS_LIST:"/admin/deal",
  ADD_DEAL:"/admin/adddeal",
  ADD_PAGE:"/admin/addpage",
  PRODUCT_LIST:"/admin/product",
  ADD_PRODUCT:"/admin/addproduct",
  PRODUCT:"/productdetail",
  USER_LIST:"/admin/user",
  ADD_USER:"/admin/adduser",
  LOGIN:"/admin/login",
  LOGINPAGE:"/login",
  REGISTERPAGE:"/register",
  MYACCOUNT:"/myaccount",
  MYCART:"/cart",
  THANKYOU:"/orderstatus",
}
